### ISSUE TITLE
JWT Signature Verification Failed - Ping contact

### ISSUE THREAD

**Issue by HelloChrome** [streembit/streembitui#57] opened 2018-01-22 13:56 UTC
Using WS browser version, - multiple errors reported with signature verification failing.  - See console in attached screenshot. - Appears to be intermittent, though - seemed
![screenshot 2 - jwt sig error](https://user-images.githubusercontent.com/34679523/35224180-03298372-ff7c-11e7-99d6-033d1617d404.png)
 to manifest during audio call.

**Comment by zsoltpardi** [comment] 2018-01-23 12:24
I am closing this as it appears caused by incorrect contactás public key. If the user have a latest contact and correct public key this shouldn't be an issue.

**Comment by zsoltpardi** [comment] 2018-01-23 12:25
We need to create a new issue to make sure the contact is updateable with the latest contact information.

**Closed** 2018-01-24 14:55 UTC
Labels: bug
